config/routes.rb
Rails.application.routes.draw do

  get 'checkout/step1'

  post 'checkout/check_s1', to: 'checkout#check_s1', as: 'check_s1'

  get 'checkout/step2'

  post 'checkout/check_s2', to: 'checkout#check_s2', as: 'check_s2'

  get 'checkout/step3'

  post 'checkout/check_s3', to: 'checkout#check_s3', as: 'check_s3'

  get 'checkout/step4'

  post 'checkout/check_s4', to: 'checkout#check_s4', as: 'check_s4'

  get 'carts/index'

  get 'carts/update'

  post 'searchs/search'

  get 'searchs/index'

  get 'stores/details/:id', to: 'stores#details', as: 'details'

  get 'customers/index'

  get 'contacts/index'

  get 'stores/index'

  get 'sessions/create'

  root to: 'pages#index'

  get '/auth/:provider/callback', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy'

  post 'customers/change_info', to: 'customers#change_info'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/ElasticsearchClient.rb
require 'multi_json'
require 'faraday'
require 'elasticsearch/api'

class ElasticsearchClient
  include Elasticsearch::API

  CONNECTION = ::Faraday::Connection.new url: 'http://localhost:9200'

  def perform_request(method, path, params, body)
    puts "--> #{method.upcase} #{path} #{params} #{body}"

    CONNECTION.run_request \
      method.downcase.to_sym,
      path,
      ( body ? MultiJson.dump(body): nil ),
      {'Content-Type' => 'application/json'}
  end
end

app/controllers/application_controller.rb
require_relative 'user_search'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    # session.delete(:user_uid)
    if @current_user.nil?
      if session[:user_uid]
        @current_user = UserSearch.get_user session[:user_uid]
      end
    else
      @current_user
    end
  end

  helper_method :current_user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  end

  def update
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def step1
  end

  def check_s1
    redirect_to checkout_step2_path
  end

  def step2
  end

  def check_s2
    redirect_to checkout_step3_path
  end

  def step3
  end

  def check_s3
    redirect_to checkout_step4_path
  end

  def step4
  end

  def check_s4
    redirect_to root_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/customers_controller.rb
require_relative 'user_search'

class CustomersController < ApplicationController
  def index
    if current_user.nil?
      redirect_to root_path
    end
    arr = %w(address province phone city email_account)
    arr.each { |item| current_user['_source']['info'][item] = '' unless current_user['_source']['info'].key? item }
  end

  def change_info
    arr = %w(address province phone city email_account)
    arr.each { |item| current_user['_source']['info'][item] = params[item] }
    current_user['_source']['info']['name'] = params['fullname']
    UserSearch.update current_user
    flash[:success] = 'Your account details has been changed!'
    redirect_to customers_index_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    flash.delete(:success)
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def index
  end

  def search
    p params['querystring']
    redirect_to searchs_index_path
  end
end

app/controllers/sessions_controller.rb
require_relative 'user_search'

class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth'].reject! { |k| k == 'credentials' || k == 'extra' }
    UserSearch.create_user auth
    session[:user_uid] = auth['provider']+auth['uid']
    redirect_to root_path
  end

  def destroy
    if current_user
      session.delete(:user_uid)
      flash.delete(:success)
    end
    redirect_to root_path
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
  end

  def details
  end
end

app/controllers/user_search.rb
require_relative 'ElasticsearchClient'

class UserSearch

  def self.create_user(auth)
    #Create client
    client = ElasticsearchClient.new

    #Call search to elastic, then parse result as JSON
    user = JSON.parse(client.search index: 'store', type: 'user', body:
        {
            "query": {
                "filtered": {
                    "query": {
                        "match": {
                            "_id": auth['provider']+auth['uid']
                        }
                    },
                    "filter": {
                        "term": {
                            "provider": auth['provider']
                        }
                    }
                }
            }
        }
    )

    #2 case to create a user: have error ( index not found... ) or search not found ( new user )
    #id = auth['provider']+auth['uid'] for all case
    if user['error'] != nil || user['hits']['total'] == 0
      client.index index: 'store', type: 'user', id: auth['provider']+auth['uid'], body: auth
    end
  end


  def self.get_user(id)

    #Create client
    client = ElasticsearchClient.new

    #Return a hash, contain user info
    JSON.parse(client.get index: 'store', type: 'user', id: id)
  end

  def self.update(auth)
    #Create client
    client = ElasticsearchClient.new
    client.index index: 'store', type: 'user', id: auth['_id'], body: auth['_source']
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/pages_controller_helper.rb
module PagesControllerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/carts/index.html.erb
<div id="heading-breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1>Shopping cart</h1>
      </div>
      <div class="col-md-6">
        <ul class="breadcrumb">
          <li><a href="index.html">Home</a>
          </li>
          <li>Shopping cart</li>
        </ul>

      </div>
    </div>
  </div>
</div>

<div id="content">
  <div class="container">

    <div class="row">
      <div class="col-md-12">
        <p class="text-muted lead">You currently have 3 item(s) in your cart.</p>
      </div>


      <div class="col-md-9 clearfix" id="basket">

        <div class="box">

          <%= form_tag checkout_step1_path, method: :get do %>
              <div class="table-responsive">
                <table class="table">
                  <thead>
                  <tr>
                    <th colspan="2">Product</th>
                    <th>Quantity</th>
                    <th>Unit price</th>
                    <th>Discount</th>
                    <th colspan="2">Total</th>
                  </tr>
                  </thead>
                  <tbody>
                  <tr>
                    <td>
                      <a href="#">
                        <img src="/img/detailsquare.jpg" alt="White Blouse Armani">
                      </a>
                    </td>
                    <td><a href="#">White Blouse Armani</a>
                    </td>
                    <td>
                      <input type="number" value="2" class="form-control">
                    </td>
                    <td>$123.00</td>
                    <td>$0.00</td>
                    <td>$246.00</td>
                    <td><a href="#"><i class="fa fa-trash-o"></i></a>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <a href="#">
                        <img src="/img/basketsquare.jpg" alt="Black Blouse Armani">
                      </a>
                    </td>
                    <td><a href="#">Black Blouse Armani</a>
                    </td>
                    <td>
                      <input type="number" value="1" class="form-control">
                    </td>
                    <td>$200.00</td>
                    <td>$0.00</td>
                    <td>$200.00</td>
                    <td><a href="#"><i class="fa fa-trash-o"></i></a>
                    </td>
                  </tr>
                  </tbody>
                  <tfoot>
                  <tr>
                    <th colspan="5">Total</th>
                    <th colspan="2">$446.00</th>
                  </tr>
                  </tfoot>
                </table>

              </div>
              <!-- /.table-responsive -->

              <div class="box-footer">
                <div class="pull-left">
                  <a href="shop-category.html" class="btn btn-default"><i class="fa fa-chevron-left"></i> Continue shopping</a>
                </div>
                <div class="pull-right">
                  <button class="btn btn-default"><i class="fa fa-refresh"></i> Update cart</button>
                  <button type="submit" class="btn btn-template-main">Proceed to checkout <i class="fa fa-chevron-right"></i>
                  </button>
                </div>
              </div>
          <% end %>

        </div>
        <!-- /.box -->

        <div class="row">
          <div class="col-md-3">
            <div class="box text-uppercase">
              <h3>You may also like these products</h3>
            </div>
          </div>

          <div class="col-md-3">
            <div class="product">
              <div class="image">
                <a href="shop-detail.html">
                  <img src="/img/product2.jpg" alt="" class="img-responsive image1">
                </a>
              </div>
              <div class="text">
                <h3><a href="shop-detail.html">Fur coat</a></h3>
                <p class="price">$143</p>

              </div>
            </div>
            <!-- /.product -->
          </div>

          <div class="col-md-3">
            <div class="product">
              <div class="image">
                <a href="shop-detail.html">
                  <img src="/img/product3.jpg" alt="" class="img-responsive image1">
                </a>
              </div>
              <div class="text">
                <h3><a href="shop-detail.html">Fur coat</a></h3>
                <p class="price">$143</p>
              </div>
            </div>
            <!-- /.product -->
          </div>

          <div class="col-md-3">
            <div class="product">
              <div class="image">
                <a href="shop-detail.html">
                  <img src="/img/product1.jpg" alt="" class="img-responsive image1">
                </a>
              </div>
              <div class="text">
                <h3><a href="shop-detail.html">Fur coat</a></h3>
                <p class="price">$143</p>
              </div>
            </div>
            <!-- /.product -->
          </div>

        </div>

      </div>
      <!-- /.col-md-9 -->

      <div class="col-md-3">
        <div class="box" id="order-summary">
          <div class="box-header">
            <h3>Order summary</h3>
          </div>
          <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>

          <div class="table-responsive">
            <table class="table">
              <tbody>
              <tr>
                <td>Order subtotal</td>
                <th>$446.00</th>
              </tr>
              <tr>
                <td>Shipping and handling</td>
                <th>$10.00</th>
              </tr>
              <tr>
                <td>Tax</td>
                <th>$0.00</th>
              </tr>
              <tr class="total">
                <td>Total</td>
                <th>$456.00</th>
              </tr>
              </tbody>
            </table>
          </div>

        </div>


        <div class="box">
          <div class="box-header">
            <h4>Coupon code</h4>
          </div>
          <p class="text-muted">If you have a coupon code, please enter it in the box below.</p>
          <form>
            <div class="input-group">

              <input type="text" class="form-control">

                                    <span class="input-group-btn">

					    <button class="btn btn-template-main" type="button"><i class="fa fa-gift"></i></button>

					</span>
            </div>
            <!-- /input-group -->
          </form>
        </div>

      </div>
      <!-- /.col-md-3 -->

    </div>

  </div>
  <!-- /.container -->
</div>
<!-- /#content -->

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>

app/views/checkout/step1.html.erb
<div id="heading-breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1>Checkout - Address</h1>
      </div>
      <div class="col-md-5">
        <ul class="breadcrumb">
          <li><a href="index.html">Home</a>
          </li>
          <li>Checkout - Address</li>
        </ul>

      </div>
    </div>
  </div>
</div>

<div id="content">
  <div class="container">

    <div class="row">

      <div class="col-md-9 clearfix" id="checkout">

        <div class="box">
          <%= form_tag check_s1_path, method: :post do %>
              <ul class="nav nav-pills nav-justified">
                <li class="active"><a href="#"><i class="fa fa-map-marker"></i><br>Address</a>
                </li>
                <li class="disabled"><a href="#"><i class="fa fa-truck"></i><br>Delivery Method</a>
                </li>
                <li class="disabled"><a href="#"><i class="fa fa-money"></i><br>Payment Method</a>
                </li>
                <li class="disabled"><a href="#"><i class="fa fa-eye"></i><br>Order Review</a>
                </li>
              </ul>

              <div class="content">
                <div class="row">
                  <div class="col-sm-6">
                    <div class="form-group">
                      <label for="firstname">Firstname</label>
                      <input type="text" class="form-control" id="firstname">
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group">
                      <label for="lastname">Lastname</label>
                      <input type="text" class="form-control" id="lastname">
                    </div>
                  </div>
                </div>
                <!-- /.row -->

                <div class="row">
                  <div class="col-sm-6">
                    <div class="form-group">
                      <label for="company">Company</label>
                      <input type="text" class="form-control" id="company">
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group">
                      <label for="street">Street</label>
                      <input type="text" class="form-control" id="street">
                    </div>
                  </div>
                </div>
                <!-- /.row -->

                <div class="row">
                  <div class="col-sm-6 col-md-3">
                    <div class="form-group">
                      <label for="city">City</label>
                      <input type="text" class="form-control" id="city">
                    </div>
                  </div>
                  <div class="col-sm-6 col-md-3">
                    <div class="form-group">
                      <label for="zip">ZIP</label>
                      <input type="text" class="form-control" id="zip">
                    </div>
                  </div>
                  <div class="col-sm-6 col-md-3">
                    <div class="form-group">
                      <label for="state">State</label>
                      <select class="form-control" id="state"></select>
                    </div>
                  </div>
                  <div class="col-sm-6 col-md-3">
                    <div class="form-group">
                      <label for="country">Country</label>
                      <select class="form-control" id="country"></select>
                    </div>
                  </div>

                  <div class="col-sm-6">
                    <div class="form-group">
                      <label for="phone">Telephone</label>
                      <input type="text" class="form-control" id="phone">
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group">
                      <label for="email">Email</label>
                      <input type="text" class="form-control" id="email">
                    </div>
                  </div>

                </div>
                <!-- /.row -->
              </div>

              <div class="box-footer">
                <div class="pull-left">
                  <%= link_to carts_index_path, class: 'btn btn-default' do %>
                      <i class="fa fa-chevron-left"></i>Back to basket<
                  <% end %>
                </div>
                <div class="pull-right">
                  <button type="submit" class="btn btn-template-main">Continue to Delivery
                    Method<i class="fa fa-chevron-right"></i>
                  </button>
                </div>
              </div>
          <% end %>
        </div>
        <!-- /.box -->


      </div>
      <!-- /.col-md-9 -->

      <div class="col-md-3">

        <div class="box" id="order-summary">
          <div class="box-header">
            <h3>Order summary</h3>
          </div>
          <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>

          <div class="table-responsive">
            <table class="table">
              <tbody>
              <tr>
                <td>Order subtotal</td>
                <th>$446.00</th>
              </tr>
              <tr>
                <td>Shipping and handling</td>
                <th>$10.00</th>
              </tr>
              <tr>
                <td>Tax</td>
                <th>$0.00</th>
              </tr>
              <tr class="total">
                <td>Total</td>
                <th>$456.00</th>
              </tr>
              </tbody>
            </table>
          </div>

        </div>

      </div>
      <!-- /.col-md-3 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
</div>
<!-- /#content -->

app/views/checkout/step2.html.erb
<div id="heading-breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1>Checkout - Delivery method</h1>
      </div>
      <div class="col-md-5">
        <ul class="breadcrumb">
          <li><a href="index.html">Home</a>
          </li>
          <li>Checkout - Delivery method</li>
        </ul>

      </div>
    </div>
  </div>
</div>

<div id="content">
  <div class="container">

    <div class="row">

      <div class="col-md-9 clearfix" id="checkout">

        <div class="box">
          <%= form_tag check_s2_path , method: :post do %>
              <ul class="nav nav-pills nav-justified">
                <li><a href="shop-checkout1.html"><i class="fa fa-map-marker"></i><br>Address</a>
                </li>
                <li class="active"><a href="#"><i class="fa fa-truck"></i><br>Delivery Method</a>
                </li>
                <li class="disabled"><a href="#"><i class="fa fa-money"></i><br>Payment Method</a>
                </li>
                <li class="disabled"><a href="#"><i class="fa fa-eye"></i><br>Order Review</a>
                </li>
              </ul>

              <div class="content">
                <div class="row">
                  <div class="col-sm-6">
                    <div class="box shipping-method">

                      <h4>USPS Next Day</h4>

                      <p>Get it right on next day - fastest option possible.</p>

                      <div class="box-footer text-center">

                        <input type="radio" name="delivery" value="delivery1">
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="box shipping-method">

                      <h4>USPS Next Day</h4>

                      <p>Get it right on next day - fastest option possible.</p>

                      <div class="box-footer text-center">

                        <input type="radio" name="delivery" value="delivery2">
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-6">
                    <div class="box shipping-method">

                      <h4>USPS Next Day</h4>

                      <p>Get it right on next day - fastest option possible.</p>

                      <div class="box-footer text-center">

                        <input type="radio" name="delivery" value="delivery3">
                      </div>
                    </div>
                  </div>
                </div>
                <!-- /.row -->

              </div>
              <!-- /.content -->

              <div class="box-footer">
                <div class="pull-left">
                  <%= link_to checkout_step1_path, class: 'btn btn-default' do %>
                      <i class="fa fa-chevron-left"></i>Back to Addresses
                  <% end %>
                </div>
                <div class="pull-right">
                  <button type="submit" class="btn btn-template-main">Continue to Payment
                    Method<i class="fa fa-chevron-right"></i>
                  </button>
                </div>
              </div>
          <% end %>
        </div>
        <!-- /.box -->


      </div>
      <!-- /.col-md-9 -->

      <div class="col-md-3">

        <div class="box" id="order-summary">
          <div class="box-header">
            <h3>Order summary</h3>
          </div>
          <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>

          <div class="table-responsive">
            <table class="table">
              <tbody>
              <tr>
                <td>Order subtotal</td>
                <th>$446.00</th>
              </tr>
              <tr>
                <td>Shipping and handling</td>
                <th>$10.00</th>
              </tr>
              <tr>
                <td>Tax</td>
                <th>$0.00</th>
              </tr>
              <tr class="total">
                <td>Total</td>
                <th>$456.00</th>
              </tr>
              </tbody>
            </table>
          </div>

        </div>

      </div>
      <!-- /.col-md-3 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
</div>
<!-- /#content -->

app/views/customers/index.html.erb
<div id="heading-breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1>My account</h1>
      </div>
      <div class="col-md-5">
        <ul class="breadcrumb">

          <li><a href="index.html">Home</a>
          </li>
          <li>My account</li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div id="content" class="clearfix">

  <div class="container">

    <div class="row">

      <!-- *** LEFT COLUMN ***
_________________________________________________________ -->

      <div class="col-md-9 clearfix" id="customer-account">

        <p class="lead">Change your personal details here.</p>
        <p class="text-muted">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis
          egestas.</p>

        <!--<div class="box">-->

        <!--<div class="heading">-->
        <!--<h3 class="text-uppercase">Change password</h3>-->
        <!--</div>-->

        <!--<form>-->
        <!--<div class="row">-->
        <!--<div class="col-sm-6">-->
        <!--<div class="form-group">-->
        <!--<label for="password_old">Old password</label>-->
        <!--<input type="password" class="form-control" id="password_old">-->
        <!--</div>-->
        <!--</div>-->
        <!--</div>-->
        <!--<div class="row">-->
        <!--<div class="col-sm-6">-->
        <!--<div class="form-group">-->
        <!--<label for="password_1">New password</label>-->
        <!--<input type="password" class="form-control" id="password_1">-->
        <!--</div>-->
        <!--</div>-->
        <!--<div class="col-sm-6">-->
        <!--<div class="form-group">-->
        <!--<label for="password_2">Retype new password</label>-->
        <!--<input type="password" class="form-control" id="password_2">-->
        <!--</div>-->
        <!--</div>-->
        <!--</div>-->
        <!--&lt;!&ndash; /.row &ndash;&gt;-->

        <!--<div class="text-center">-->
        <!--<button type="submit" class="btn btn-template-main"><i class="fa fa-save"></i> Save new password</button>-->
        <!--</div>-->
        <!--</form>-->

        <!--</div>-->
        <!--&lt;!&ndash; /.box &ndash;&gt;-->


        <div class="box clearfix">
          <div class="heading">
            <h3 class="text-uppercase">Personal details</h3>
          </div>

          <%= form_tag customers_change_info_path, method: :post do %>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="fullname">Full name</label>
                    <input type="text" class="form-control" id="fullname" name="fullname" value="<%= current_user['_source']['info']['name'] %>">
                  </div>
                </div>
              </div>
              <!-- /.row -->

              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="address">Address</label>
                    <input type="text" class="form-control" id="address" name="address" value="<%= current_user['_source']['info']['address'] %>">
                  </div>
                </div>

                <div class="col-sm-6 col-md-3">
                  <div class="form-group">
                    <label for="city">City</label>
                    <input type="text" class="form-control" id="city" name="city" value="<%= current_user['_source']['info']['city'] %>">
                  </div>
                </div>
                <div class="col-sm-6 col-md-3">
                  <div class="form-group">
                    <label for="province">Province</label>
                    <input type="text" class="form-control" id="province" name="province" value="<%= current_user['_source']['info']['province'] %>">
                  </div>
                </div>
              </div>
              <!-- /.row -->

              <div class="row">

                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="phone">Telephone</label>
                    <input type="text" class="form-control" id="phone" name="phone" value="<%= current_user['_source']['info']['phone'] %>">
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="email_account">Email</label>
                    <input type="text" class="form-control" id="email_account" name="email_account" value="<%= current_user['_source']['info']['email_account'] %>">
                  </div>
                </div>
                <div class="col-sm-12 text-center">
                  <div class="form-group">
                    <% flash.each do |key, value| %>
                        <div class="alert alert-<%= key %>"><%= value %></div>
                    <% end %>
                  </div>
                </div>
                <div class="col-sm-12 text-center">
                  <button type="submit" class="btn btn-template-main"><i class="fa fa-save"></i> Save changes</button>

                </div>

              </div>

          <% end %>

        </div>

      </div>
      <!-- /.col-md-9 -->

      <!-- *** LEFT COLUMN END *** -->

      <!-- *** RIGHT COLUMN ***
_________________________________________________________ -->

      <div class="col-md-3">
        <!-- *** CUSTOMER MENU ***
_________________________________________________________ -->
        <div class="panel panel-default sidebar-menu">

          <div class="panel-heading">
            <h3 class="panel-title">Customer section</h3>
          </div>

          <div class="panel-body">

            <ul class="nav nav-pills nav-stacked">
              <li>
                <a href="customer-orders.html"><i class="fa fa-list"></i> My orders</a>
              </li>
              <li>
                <a href="customer-wishlist.html"><i class="fa fa-heart"></i> My wishlist</a>
              </li>
              <li class="active">
                <a href="customer-account.html"><i class="fa fa-user"></i> My account</a>
              </li>
              <li>
                <a href="index.html"><i class="fa fa-sign-out"></i> Logout</a>
              </li>
            </ul>
          </div>

        </div>
        <!-- /.col-md-3 -->

        <!-- *** CUSTOMER MENU END *** -->
      </div>

      <!-- *** RIGHT COLUMN END *** -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
</div>
<!-- /#content -->